"""add_vendor_indices

Revision ID: 65e45850d51c
Revises: 202886b2953e
Create Date: 2026-01-16 22:34:22.167610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65e45850d51c'
down_revision: Union[str, None] = '202886b2953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soc_profiles_bluetooth_id'), table_name='soc_profiles')
    op.drop_index(op.f('ix_soc_profiles_id'), table_name='soc_profiles')
    op.drop_index(op.f('ix_soc_profiles_phone_number'), table_name='soc_profiles')
    op.drop_index(op.f('ix_soc_profiles_soc_id'), table_name='soc_profiles')
    op.drop_table('soc_profiles')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_deleted')
    op.create_index(op.f('ix_vendors_company_name'), 'vendors', ['company_name'], unique=False)
    op.create_index(op.f('ix_vendors_verification_status'), 'vendors', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_verification_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_company_name'), table_name='vendors')
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscription_plan', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subscription_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('organizations_pkey'))
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('soc_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soc_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gov_id_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bluetooth_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('soc_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('soc_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('soc_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_soc_profiles_soc_id'), 'soc_profiles', ['soc_id'], unique=True)
    op.create_index(op.f('ix_soc_profiles_phone_number'), 'soc_profiles', ['phone_number'], unique=True)
    op.create_index(op.f('ix_soc_profiles_id'), 'soc_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_soc_profiles_bluetooth_id'), 'soc_profiles', ['bluetooth_id'], unique=True)
    # ### end Alembic commands ###
