"""add_check_in_out_location_to_visits

Revision ID: 84880a28f7c4
Revises: 93a89dfba37a
Create Date: 2026-01-24 22:39:40.171220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84880a28f7c4'
down_revision: Union[str, None] = '93a89dfba37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.add_column('visits', sa.Column('check_in_location', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('check_out_location', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'check_out_location')
    op.drop_column('visits', 'check_in_location')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    # ### end Alembic commands ###
