"""add_company_fields_to_vendor

Revision ID: 93a89dfba37a
Revises: 65e45850d51c
Create Date: 2026-01-16 23:11:31.145120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a89dfba37a'
down_revision: Union[str, None] = '65e45850d51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soc_profiles_id'), table_name='soc_profiles')
    op.drop_index(op.f('ix_soc_profiles_soc_id'), table_name='soc_profiles')
    op.drop_table('soc_profiles')
    op.add_column('vendors', sa.Column('website', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('gstin', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'logo_url')
    op.drop_column('vendors', 'description')
    op.drop_column('vendors', 'gstin')
    op.drop_column('vendors', 'website')
    op.create_table('soc_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('soc_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('service_category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bluetooth_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gov_id_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('soc_profiles_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('soc_profiles_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('soc_profiles_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_soc_profiles_soc_id'), 'soc_profiles', ['soc_id'], unique=True)
    op.create_index(op.f('ix_soc_profiles_id'), 'soc_profiles', ['id'], unique=False)
    # ### end Alembic commands ###
