"""add_qr_code_fields_to_vendors

Revision ID: a1b2c3d4e5f6
Revises: 84880a28f7c4
Create Date: 2026-01-25 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e8d9c0b1a2'
down_revision: Union[str, None] = '84880a28f7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('qr_code_data', sa.Text(), nullable=True))
    op.add_column('vendors', sa.Column('qr_code_image_url', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('qr_code_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'qr_code_generated_at')
    op.drop_column('vendors', 'qr_code_image_url')
    op.drop_column('vendors', 'qr_code_data')
    # ### end Alembic commands ###
